/**
 * The capture contract's exclusion rules, one fixture per noise family.
 * These are the families a naive `role === "user"` filter lets straight
 * through -- each one really appears in the 90MB session transcript this
 * filter was built against, and each would otherwise be captured as if a
 * human had typed it.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { filterTranscriptEntry, reposForEntry, type FilteredEntry, type RepoResolver } from "./transcript-filter.js";

function userEntry(content: unknown, extra: Record<string, unknown> = {}): unknown {
  return { type: "user", timestamp: "2026-09-05T12:00:00.000Z", message: { role: "user", content }, ...extra };
}

test("filterTranscriptEntry: a genuine human turn is kept", () => {
  const result = filterTranscriptEntry(userEntry("Next, I want to implement a view in monitor where I can select multiple repos."));
  assert.equal(result.turn?.role, "user");
  assert.match(result.turn?.text ?? "", /select multiple repos/);
  assert.equal(result.turn?.ts, "2026-09-05T12:00:00.000Z");
});

test("filterTranscriptEntry: assistant prose is kept", () => {
  const result = filterTranscriptEntry({
    type: "assistant",
    message: { role: "assistant", content: [{ type: "text", text: "The daemon reported a stale version the whole time." }] },
  });
  assert.equal(result.turn?.role, "assistant");
  assert.equal(result.turn?.text, "The daemon reported a stale version the whole time.");
});

test("filterTranscriptEntry: a compaction summary is dropped -- capturing it would capture the decay this exists to route around", () => {
  const result = filterTranscriptEntry(
    userEntry("This session is being continued from a previous conversation that ran out of context.\n\nSummary:\n1. Primary Request and Intent:", {
      isCompactSummary: true,
    }),
  );
  assert.equal(result.turn, undefined);
});

test("filterTranscriptEntry: the <command-name> family is dropped", () => {
  const result = filterTranscriptEntry(userEntry("<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>"));
  assert.equal(result.turn, undefined);
});

test("filterTranscriptEntry: <local-command-stdout> is dropped", () => {
  const result = filterTranscriptEntry(userEntry("<local-command-stdout>Compacted (ctrl+o to see full summary)</local-command-stdout>"));
  assert.equal(result.turn, undefined);
});

test("filterTranscriptEntry: an isMeta turn (the local-command caveat) is dropped", () => {
  const result = filterTranscriptEntry(
    userEntry("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>", { isMeta: true }),
  );
  assert.equal(result.turn, undefined);
});

test("filterTranscriptEntry: a <system-reminder> block is stripped out of an otherwise real turn", () => {
  const result = filterTranscriptEntry(userEntry("Fix the watermark bug.\n<system-reminder>\nThis is a reminder about CLAUDE.md.\n</system-reminder>"));
  assert.equal(result.turn?.text, "Fix the watermark bug.");
});

test("filterTranscriptEntry: a turn that is nothing but a <system-reminder> is dropped entirely", () => {
  const result = filterTranscriptEntry(userEntry("<system-reminder>Background context, not a human turn.</system-reminder>"));
  assert.equal(result.turn, undefined);
});

test("filterTranscriptEntry: hook additionalContext (an `attachment` entry) is dropped", () => {
  const result = filterTranscriptEntry({
    type: "attachment",
    attachment: { type: "hook_success", hookEvent: "SessionStart", stdout: '{"hookSpecificOutput":{"additionalContext":"twing design coordinator: ..."}}' },
  });
  assert.equal(result.turn, undefined);
  assert.deepEqual(result.paths, []);
});

test("filterTranscriptEntry: tool results are dropped whole, Bash output included", () => {
  const result = filterTranscriptEntry(
    userEntry([{ tool_use_id: "toolu_01", type: "tool_result", content: "sig_len=6164\nsome very long command output", is_error: false }]),
  );
  assert.equal(result.turn, undefined);
});

test("filterTranscriptEntry: a tool call contributes its file path and nothing else", () => {
  const result = filterTranscriptEntry({
    type: "assistant",
    cwd: "/Users/dev/proj",
    message: {
      role: "assistant",
      content: [{ type: "tool_use", id: "toolu_02", name: "Edit", input: { file_path: "/Users/dev/proj/src/a.ts", old_string: "x", new_string: "y" } }],
    },
  });
  assert.equal(result.turn, undefined);
  assert.deepEqual(result.paths.sort(), ["/Users/dev/proj", "/Users/dev/proj/src/a.ts"]);
});

test("filterTranscriptEntry: a Bash command body is not mistaken for a path", () => {
  const result = filterTranscriptEntry({
    type: "assistant",
    message: { role: "assistant", content: [{ type: "tool_use", name: "Bash", input: { command: "cat /etc/passwd | grep secret" } }] },
  });
  assert.deepEqual(result.paths, []);
});

test("filterTranscriptEntry: nested edits contribute their paths too", () => {
  const result = filterTranscriptEntry({
    type: "assistant",
    message: {
      role: "assistant",
      content: [{ type: "tool_use", name: "MultiEdit", input: { edits: [{ file_path: "a.ts" }, { file_path: "b.ts" }] } }],
    },
  });
  assert.deepEqual(result.paths, ["a.ts", "b.ts"]);
});

test("filterTranscriptEntry: assistant thinking blocks are dropped", () => {
  const result = filterTranscriptEntry({
    type: "assistant",
    message: { role: "assistant", content: [{ type: "thinking", thinking: "internal reasoning", signature: "EogkCqgBCBEYAipA" }] },
  });
  assert.equal(result.turn, undefined);
});

test("filterTranscriptEntry: a per-entry cwd is reported -- one session can span several repos", () => {
  const result = filterTranscriptEntry(userEntry("hello", { cwd: "/Users/dev/other-repo" }));
  assert.equal(result.cwd, "/Users/dev/other-repo");
  assert.deepEqual(result.paths, ["/Users/dev/other-repo"]);
});

test("filterTranscriptEntry: junk input degrades to captured-nothing rather than throwing", () => {
  for (const junk of [null, undefined, 42, "a string", {}, { type: "user" }, { type: "user", message: { content: 7 } }]) {
    const result = filterTranscriptEntry(junk);
    assert.equal(result.turn, undefined);
    assert.ok(Array.isArray(result.paths));
  }
});

// Repo attribution. Capture consent keys on which repositories a session
// touched, so these decide what gets captured at all -- a fake resolver
// keeps them pure and lets the awkward shapes (no repo, no cwd, relative
// paths) be stated directly rather than staged on disk.

/** Treats any path under `/repos/<name>` as belonging to that repo, and
 * everything else as outside every repo. */
const fakeResolver: RepoResolver = (absPath) => {
  const match = /^(\/repos\/[^/]+)(?:\/|$)/.exec(absPath);
  return match ? match[1] : undefined;
};

function entry(paths: string[], cwd?: string): FilteredEntry {
  return { paths, cwd };
}

test("reposForEntry: maps touched paths to their repo roots, deduped and in first-seen order", () => {
  const result = reposForEntry(entry(["/repos/api/src/a.ts", "/repos/ui/src/b.tsx", "/repos/api/src/c.ts"]), fakeResolver);
  assert.deepEqual(result, ["/repos/api", "/repos/ui"]);
});

// The reason this function exists rather than reading `paths` directly.
// `filterTranscriptEntry` puts the entry's cwd in `paths`, and every entry
// in a session carries the same one -- all 42,117 in the transcript this
// was built against named twing-cli, while the tool calls spanned three
// repos. Attributing on cwd would collapse every session to one repo.
test("reposForEntry: the entry's own cwd is not a touch", () => {
  const result = reposForEntry(entry(["/repos/ui/src/b.tsx", "/repos/api"], "/repos/api"), fakeResolver);
  assert.deepEqual(result, ["/repos/ui"], "cwd is the caller's separate input, never a per-entry signal");
});

// A path outside every repo must read as "no repo", never as a repo of its
// own -- otherwise a scratch file would act like a project that never
// opted in, and hard-stop the consent walk on nothing.
test("reposForEntry: paths outside every repo contribute nothing", () => {
  const result = reposForEntry(entry(["/Users/dev/.claude/plans/some-plan.md", "/tmp/scratch.txt"]), fakeResolver);
  assert.deepEqual(result, []);
});

test("reposForEntry: relative paths resolve against the entry's cwd", () => {
  const result = reposForEntry(entry(["src/a.ts"], "/repos/api"), fakeResolver);
  assert.deepEqual(result, ["/repos/api"]);
});

test("reposForEntry: a relative path with no cwd is skipped rather than guessed at", () => {
  const result = reposForEntry(entry(["src/a.ts"]), fakeResolver);
  assert.deepEqual(result, [], "misattributing a touch is the one error this must not make");
});

test("reposForEntry: a real filtered entry's tool-call paths flow straight through", () => {
  const filtered = filterTranscriptEntry({
    type: "assistant",
    message: {
      role: "assistant",
      content: [{ type: "tool_use", name: "Edit", input: { file_path: "/repos/ui/src/App.tsx" } }],
    },
    cwd: "/repos/api",
  });
  assert.deepEqual(reposForEntry(filtered, fakeResolver), ["/repos/ui"]);
});
